import { defineCollection } from 'astro:content';
import { z } from 'astro/zod';

const caseSchema = z.object({
	lang: z.enum(['es', 'en']),
	slug: z.string(),
	counterpartSlug: z.string(),
	title: z.string(),
	client: z.string(),
	summary: z.string(),
	context: z.string(),
	problem: z.string(),
	role: z.string(),
	diagnosis: z.array(z.string()),
	intervention: z.array(z.string()),
	decisions: z.array(z.string()),
	stack: z.array(z.string()),
	evidence: z.array(z.string()),
	results: z.array(z.string()),
	limitations: z.array(z.string()),
	learnings: z.array(z.string()),
	cta: z.string(),
	verification: z.object({
		status: z.enum(['pending', 'requires-review', 'verified']),
		asOf: z.string().nullable(),
		source: z.string(),
	}),
	publication: z.object({
		publish: z.boolean(),
		featured: z.boolean(),
	}),
	internalClaims: z
		.array(
			z.object({
				label: z.string(),
				value: z.number(),
				publish: z.literal(false),
				status: z.literal('requires-review'),
				asOf: z.null(),
				source: z.literal('prompt'),
			}),
		)
		.optional(),
});

const shared = {
	stack: ['Discovery', 'Information architecture', 'Interface design'],
	evidence: ['Project reference supplied in the initial brief; supporting artifacts are pending review.'],
	results: ['No quantitative outcome is published until source material is validated.'],
	verification: { status: 'pending' as const, asOf: null, source: 'initial project brief' },
	publication: { publish: true, featured: false },
};

const cases = [
	{
		id: 'es-wu-nutrition-dumo',
		...shared,
		lang: 'es',
		slug: 'wu-nutrition-dumo',
		counterpartSlug: 'wu-nutrition-dumo',
		title: 'WU Nutrition / DUMO',
		client: 'WU Nutrition / DUMO',
		summary: 'Estructura preliminar de un caso de producto digital; la evidencia pública sigue pendiente.',
		context: 'Proyecto citado en el brief como referencia de trabajo.',
		problem: 'El problema, alcance y punto de partida requieren validación documental antes de publicarse.',
		role: 'Participación por documentar.',
		diagnosis: ['Hipótesis y hallazgos pendientes de fuente.'],
		intervention: ['Trabajo realizado pendiente de reconstrucción verificable.'],
		decisions: ['No publicar afirmaciones específicas sin respaldo.'],
		evidence: ['Referencia del proyecto en el brief inicial; artefactos pendientes de revisión.'],
		results: ['No se publican resultados cuantitativos hasta validar fuentes.'],
		limitations: ['No hay materiales verificables incorporados todavía.'],
		learnings: ['La trazabilidad de evidencia es parte del caso, no una nota posterior.'],
		cta: 'Solicita el contexto disponible de este proyecto.',
		publication: { publish: true, featured: true },
	},
	{
		id: 'en-wu-nutrition-dumo',
		...shared,
		lang: 'en',
		slug: 'wu-nutrition-dumo',
		counterpartSlug: 'wu-nutrition-dumo',
		title: 'WU Nutrition / DUMO',
		client: 'WU Nutrition / DUMO',
		summary: 'Preliminary structure for a digital product case; public evidence is still pending.',
		context: 'Project named in the brief as a work reference.',
		problem: 'The problem, scope, and starting point need documentary validation before publication.',
		role: 'Contribution to be documented.',
		diagnosis: ['Hypotheses and findings are awaiting sources.'],
		intervention: ['Completed work awaits a verifiable reconstruction.'],
		decisions: ['Do not publish specific claims without support.'],
		limitations: ['No verifiable materials have been incorporated yet.'],
		learnings: ['Evidence traceability belongs inside the case, not in an afterthought.'],
		cta: 'Ask for the currently available project context.',
		publication: { publish: true, featured: true },
	},
	{
		id: 'es-bloqio-cro-apps',
		...shared,
		lang: 'es',
		slug: 'bloqio-cro-apps',
		counterpartSlug: 'bloqio-cro-apps',
		title: 'Bloqio CRO Apps — Prometeo / Hermes',
		client: 'Bloqio',
		summary: 'Caso en preparación sobre aplicaciones CRO; sin métricas públicas no verificadas.',
		context: 'Prometeo y Hermes se registran como referencias del brief.',
		problem: 'Objetivos y restricciones todavía no cuentan con fuentes publicables.',
		role: 'Participación por documentar.',
		diagnosis: ['Recopilación de contexto pendiente.'],
		intervention: ['Intervenciones por confirmar con artefactos.'],
		decisions: ['Separar hechos, hipótesis y resultados.'],
		evidence: ['Nombres de producto provistos en el brief; evidencia pendiente.'],
		results: ['Resultados pendientes de verificación.'],
		limitations: ['No se atribuyen mejoras de conversión.'],
		learnings: ['La prudencia evita convertir una referencia en una promesa.'],
		cta: 'Conversemos sobre optimización basada en evidencia.',
	},
	{
		id: 'en-bloqio-cro-apps',
		...shared,
		lang: 'en',
		slug: 'bloqio-cro-apps',
		counterpartSlug: 'bloqio-cro-apps',
		title: 'Bloqio CRO Apps — Prometeo / Hermes',
		client: 'Bloqio',
		summary: 'Case in preparation about CRO applications, without unverified public metrics.',
		context: 'Prometeo and Hermes are recorded as references from the brief.',
		problem: 'Goals and constraints do not yet have publishable sources.',
		role: 'Contribution to be documented.',
		diagnosis: ['Context collection is pending.'],
		intervention: ['Interventions need confirmation through artifacts.'],
		decisions: ['Keep facts, hypotheses, and outcomes distinct.'],
		evidence: ['Product names supplied in the brief; evidence pending.'],
		results: ['Outcomes are pending verification.'],
		limitations: ['No conversion improvements are attributed.'],
		learnings: ['Restraint prevents turning a reference into a promise.'],
		cta: 'Let’s discuss evidence-led optimization.',
	},
	{
		id: 'es-bloqio-builder',
		...shared,
		lang: 'es',
		slug: 'bloqio-builder',
		counterpartSlug: 'bloqio-builder',
		title: 'Bloqio Builder',
		client: 'Bloqio',
		summary: 'Fundación de caso para una herramienta de creación; alcance y resultados siguen en revisión.',
		context: 'Bloqio Builder figura como proyecto del portafolio inicial.',
		problem: 'La historia de producto debe reconstruirse desde fuentes revisables.',
		role: 'Participación por documentar.',
		diagnosis: ['Inventario de evidencia pendiente.'],
		intervention: ['Flujos y decisiones por documentar.'],
		decisions: ['Mantener fuera de publicación las cifras no validadas.'],
		evidence: ['Existencia del proyecto indicada en el brief.'],
		results: ['Sin resultados públicos verificados.'],
		limitations: ['Las cifras recibidas no tienen fecha ni fuente independiente.'],
		learnings: ['Una cifra sin procedencia no constituye evidencia pública.'],
		cta: 'Solicita una conversación sobre sistemas de producto.',
		internalClaims: [
			{ label: 'users', value: 57, publish: false, status: 'requires-review', asOf: null, source: 'prompt' },
			{ label: 'pages', value: 45, publish: false, status: 'requires-review', asOf: null, source: 'prompt' },
		],
	},
	{
		id: 'en-bloqio-builder',
		...shared,
		lang: 'en',
		slug: 'bloqio-builder',
		counterpartSlug: 'bloqio-builder',
		title: 'Bloqio Builder',
		client: 'Bloqio',
		summary: 'Case foundation for a creation tool; scope and outcomes remain under review.',
		context: 'Bloqio Builder appears as a project in the initial portfolio brief.',
		problem: 'The product story must be rebuilt from reviewable sources.',
		role: 'Contribution to be documented.',
		diagnosis: ['Evidence inventory is pending.'],
		intervention: ['Flows and decisions need documentation.'],
		decisions: ['Keep unvalidated figures out of published output.'],
		evidence: ['Project existence stated in the brief.'],
		results: ['No verified public outcomes.'],
		limitations: ['Supplied figures have no date or independent source.'],
		learnings: ['A number without provenance is not public evidence.'],
		cta: 'Ask for a conversation about product systems.',
		internalClaims: [
			{ label: 'users', value: 57, publish: false, status: 'requires-review', asOf: null, source: 'prompt' },
			{ label: 'pages', value: 45, publish: false, status: 'requires-review', asOf: null, source: 'prompt' },
		],
	},
	{
		id: 'es-la-carniceria-virtual',
		...shared,
		lang: 'es',
		slug: 'la-carniceria-virtual',
		counterpartSlug: 'la-carniceria-virtual',
		title: 'La Carnicería Virtual',
		client: 'La Carnicería Virtual',
		summary: 'Placeholder editorial para documentar un proyecto comercial sin extrapolar resultados.',
		context: 'Referencia de proyecto incluida en el brief.',
		problem: 'Faltan contexto, objetivos y evidencia revisada.',
		role: 'Participación por documentar.',
		diagnosis: ['Investigación pendiente de incorporación.'],
		intervention: ['Alcance pendiente de confirmación.'],
		decisions: ['Publicar únicamente lo trazable.'],
		evidence: ['Nombre del proyecto provisto en el brief.'],
		results: ['Evidencia de resultados pendiente.'],
		limitations: ['Caso todavía incompleto.'],
		learnings: ['La estructura permite completar el caso sin reescribir su fundamento.'],
		cta: 'Consulta por proyectos de comercio digital.',
	},
	{
		id: 'en-la-carniceria-virtual',
		...shared,
		lang: 'en',
		slug: 'la-carniceria-virtual',
		counterpartSlug: 'la-carniceria-virtual',
		title: 'La Carnicería Virtual',
		client: 'La Carnicería Virtual',
		summary: 'Editorial placeholder for documenting a commerce project without extrapolating outcomes.',
		context: 'Project reference included in the brief.',
		problem: 'Context, goals, and reviewed evidence are missing.',
		role: 'Contribution to be documented.',
		diagnosis: ['Research has not yet been incorporated.'],
		intervention: ['Scope is awaiting confirmation.'],
		decisions: ['Publish only what can be traced.'],
		evidence: ['Project name supplied in the brief.'],
		results: ['Outcome evidence is pending.'],
		limitations: ['The case is still incomplete.'],
		learnings: ['The structure can absorb evidence without rewriting its foundation.'],
		cta: 'Ask about digital commerce projects.',
	},
	{
		id: 'es-come-verde',
		...shared,
		lang: 'es',
		slug: 'come-verde',
		counterpartSlug: 'come-verde',
		title: 'Come Verde',
		client: 'Come Verde',
		summary: 'Caso inicial de marca y producto digital, marcado explícitamente como evidencia pendiente.',
		context: 'Proyecto citado en el brief de partida.',
		problem: 'La definición del reto requiere fuentes adicionales.',
		role: 'Participación por documentar.',
		diagnosis: ['Supuestos pendientes de contraste.'],
		intervention: ['Entregables pendientes de inventario.'],
		decisions: ['Evitar atribuciones de impacto no demostradas.'],
		evidence: ['Referencia del proyecto en el brief.'],
		results: ['No hay resultados verificados para publicación.'],
		limitations: ['Narrativa todavía preliminar.'],
		learnings: ['Marcar vacíos de evidencia hace el caso más honesto.'],
		cta: 'Hablemos de claridad estratégica y producto.',
	},
	{
		id: 'en-come-verde',
		...shared,
		lang: 'en',
		slug: 'come-verde',
		counterpartSlug: 'come-verde',
		title: 'Come Verde',
		client: 'Come Verde',
		summary: 'Initial brand and digital product case, explicitly marked as evidence pending.',
		context: 'Project named in the starting brief.',
		problem: 'The challenge definition needs additional sources.',
		role: 'Contribution to be documented.',
		diagnosis: ['Assumptions need to be challenged.'],
		intervention: ['Deliverables await an inventory.'],
		decisions: ['Avoid unsupported impact attribution.'],
		evidence: ['Project reference in the brief.'],
		results: ['No verified outcomes are available for publication.'],
		limitations: ['The narrative remains preliminary.'],
		learnings: ['Marking evidence gaps makes the case more honest.'],
		cta: 'Let’s discuss strategic clarity and product.',
	},
];

const caseStudies = defineCollection({
	loader: async () => cases,
	schema: caseSchema,
});

export const collections = { cases: caseStudies };
